---
- include: ./playbooks/common.yml
  when: ansible_role == "bastion"

- include: ./playbooks/frontend.yml
  when: ansible_role == "frontend"

- include: ./playbooks/backend.yml
  when: ansible_role == "backend"

